#!/bin/bash
# First-boot installer for the webui instance. Invoked by the thin-loader UserData with:
#   WEBUI_PORT, DATA_STACK, DATA_API_STAGE, ARTIFACT_BUCKET, ARTIFACT_PREFIX
set -xeuo pipefail
exec > /var/log/webui-bootstrap.log 2>&1

: "${WEBUI_PORT:=8080}"
: "${DATA_STACK:=video-analyzer-stack}"
: "${DATA_API_STAGE:=development}"
: "${ARTIFACT_BUCKET:?ARTIFACT_BUCKET is required}"
: "${ARTIFACT_PREFIX:?ARTIFACT_PREFIX is required}"

S3_BASE="s3://${ARTIFACT_BUCKET}/${ARTIFACT_PREFIX}webui"

# 0. defensive aws CLI check (the loader should have ensured it; verify and fail loudly).
if ! command -v aws >/dev/null 2>&1; then
  echo "ERROR: aws CLI not found on PATH. Cannot fetch artifacts. Aborting." >&2
  exit 1
fi

# 1. non-root system user (http.server binds a >1024 port, so no root needed)
id -u webui >/dev/null 2>&1 || useradd -r -s /sbin/nologin webui

# 2. fetch + unpack the static web-ui into /opt/webui.
#    Wipe the directory first so files deleted from the source on a redeploy do
#    NOT linger on the instance (apigw.js is regenerated by genconfig at start).
rm -rf /opt/webui
mkdir -p /opt/webui
aws s3 cp "${S3_BASE}/web-ui.tgz" /tmp/web-ui.tgz
tar -xzf /tmp/web-ui.tgz -C /opt/webui
rm -f /tmp/web-ui.tgz

# 3. fetch the apigw.js generator + the systemd unit
aws s3 cp "${S3_BASE}/webui-genconfig.sh" /opt/webui-genconfig.sh
chmod +x /opt/webui-genconfig.sh
aws s3 cp "${S3_BASE}/webui.service" /etc/systemd/system/webui.service

# 4. environment file consumed by the unit AND the generator
cat > /etc/webui.env <<EOF
WEBUI_PORT=${WEBUI_PORT}
DATA_STACK=${DATA_STACK}
DATA_API_STAGE=${DATA_API_STAGE}
EOF

# 5. ownership so the webui user can read files and (re)write src/apigw.js
chown -R webui:webui /opt/webui

# 6. enable + start (ExecStartPre regenerates apigw.js on every start, incl. reboot)
systemctl daemon-reload
systemctl enable --now webui.service
echo "webui bootstrap complete (port ${WEBUI_PORT})"
